groups:

  - name: a1_franka
    match: "(?=.*a1)(?=.*franka)"
    total_weight: 0.25
    inside: frames_pow
    gamma: 1.0

  - name: a1_lift2
    match: "(?=.*a1)(?=.*lift2)"
    total_weight: 0.3
    inside: frames_pow
    gamma: 1.0

  - name: a1_split_aloha
    match: "(?=.*a1)(?=.*split_aloha)"
    total_weight: 0.3
    inside: frames_pow
    gamma: 1.0

  - name: a1_genie1
    match: "(?=.*a1)(?=.*genie1)"
    total_weight: 0.1
    inside: frames_pow
    gamma: 1.0

  - name: a1_acone
    match: "(?=.*a1)(?=.*acone)"
    total_weight: 0.05
    inside: frames_pow
    gamma: 1.0

default:
  total_weight: 0.1
  inside: frames_pow
  gamma: 1.0
